import Vue from "vue";
import {
  Avatar,
  Button,
  ColorPicker,
  Cascader,
  Container,
  Col,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Dialog,
  Form,
  FormItem,
  Header,
  Input,
  Loading,
  MessageBox,
  Message,
  Main,
  Menu,
  MenuItem,
  Slider,
  Option,
  Select,
  Table,
  TableColumn,
  Tree,
  Tag,
  Tooltip,
  Upload,
  Switch,
  Card,
  Pagination,
  Progress,
  RadioGroup,
  Row,
  Radio,
  InputNumber,
  Steps,
  Step,
  Drawer,
  Timeline,
  TimelineItem
} from "element-ui";
Vue.use(Input);
Vue.use(Loading);
Vue.use(Avatar);
Vue.use(Dropdown);
Vue.use(DropdownItem);
Vue.use(DropdownMenu);
Vue.use(Dialog);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(ColorPicker);
Vue.use(Slider);
Vue.use(Cascader);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Select);
Vue.use(Button);
Vue.use(Row);
Vue.use(Col);
Vue.use(Option);
Vue.use(Upload);
Vue.use(Header);
Vue.use(Main);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Container);
Vue.use(Switch);
Vue.use(Card);
Vue.use(Pagination);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(Tree);
Vue.use(InputNumber);
Vue.use(Progress);
Vue.use(Tooltip);
Vue.use(Tag);
Vue.use(Steps);
Vue.use(Step);
Vue.use(Drawer);
Vue.use(Timeline);
Vue.use(TimelineItem);
export { MessageBox, Message };
